server:
  port: 8083

spring:

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:h2:~/oauth2/database/resource-server
      password: sa
      username: sa
      hikari :
        minimumIdle: 5
        maximumPoolSize: 20
        idleTimeout : 30000
        poolName : SpringBootJPAHikariCP
        maxLifetime : 2000000
        connectionTimeout : 30000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#flyway
  flyway:
    url       : ${spring.datasource.jdbc-url}
    user      : ${spring.datasource.username}
    password  : ${spring.datasource.password}

# oauth params
client:
  client-id:     curl_client
  client-secret: password
resource:
  id: product_api
  token-info-uri: http://localhost:8081/oauth/check_token