version: '3'
services:
  oauth2-authorization-server:
#   build: oauth2-authorization-server
    image: "antoniocaccamo/oauth2-authorization-server"
    ports:
      - "8081:8081"
    networks: 
      - oauth2-net

  oauth2-resource-server:
#   build: oauth2-resource-server
    image: "antoniocaccamo/oauth2-resource-server"
    ports:
      - "8083:8083"
    depends_on: 
      - "oauth2-authorization-server"
    networks: 
      - oauth2-net
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure

networks: 
    oauth2-net: