-- 
INSERT INTO OAUTH_CLIENT_DETAILS(
    CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, 
    SCOPE, AUTHORIZED_GRANT_TYPES, WEB_SERVER_REDIRECT_URI, AUTHORITIES, 
    ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE             
) VALUES(
    'curl_client','product_api', '$2a$10$PcPSN9XxabgdRLgrV0hGduQUV.bK3anhe8ypx0GZIO0/lSGwk1Wha', 
    'read,write', 'client_credentials,password', 'http://127.0.0.1', 'ROLE_PRODUCT_ADMIN', 
    7200, 0, NULL, 'true'
);