--
INSERT INTO AUTHORITY (ID, AUTHORITY ) VALUES(1,'ROLE_OAUTH_ADMIN');
INSERT INTO AUTHORITY (ID, AUTHORITY ) VALUES(2,'ROLE_RESOURCE_ADMIN');
INSERT INTO AUTHORITY (ID, AUTHORITY ) VALUES(3,'ROLE_PRODUCT_ADMIN');

--
INSERT INTO CREDENTIALS (ID, ENABLED, NAME, PASSWORD,VERSION) VALUES(1, '1','oauth_admin'   ,'$2a$10$PcPSN9XxabgdRLgrV0hGduQUV.bK3anhe8ypx0GZIO0/lSGwk1Wha','0');
INSERT INTO CREDENTIALS (ID, ENABLED, NAME, PASSWORD,VERSION) VALUES(2, '1','resource_admin','$2a$10$PcPSN9XxabgdRLgrV0hGduQUV.bK3anhe8ypx0GZIO0/lSGwk1Wha','0');
INSERT INTO CREDENTIALS (ID, ENABLED, NAME, PASSWORD,VERSION) VALUES(3, '1','product_admin' ,'$2a$10$PcPSN9XxabgdRLgrV0hGduQUV.bK3anhe8ypx0GZIO0/lSGwk1Wha','0');

--
INSERT INTO CREDENTIALS_AUTHORITIES (CREDENTIALS_ID, AUTHORITIES_ID)VALUES (1,1);
INSERT INTO CREDENTIALS_AUTHORITIES (CREDENTIALS_ID, AUTHORITIES_ID)VALUES (2,2);
INSERT INTO CREDENTIALS_AUTHORITIES (CREDENTIALS_ID, AUTHORITIES_ID)VALUES (3,3);
